### ISSUE TITLE
relationship to https://github.com/tonis2/c3-vscode ?

### ISSUE THREAD

**Issue by felixf4xu** [c3lang/vscode-c3#6]
Hi,

When I search c3 in VSCode extensions, I got C3 by tonis, which is from https://github.com/tonis2/c3-vscode

But from this repo's address of `https://github.com/c3lang/vscode-c3`, this one should be more _official_, so any relationship between the 2 repos?

**Comment by tonis2** [comment]
I'm now starting to use below namespace in vscode for the extension, and the code in it, will match this repository, so there's less confusion.

https://marketplace.visualstudio.com/items?itemName=c3.vscode-c3
